---
- name: Check if yay is installed
  ansible.builtin.command: which yay
  register: yay_check
  changed_when: false
  failed_when: false

- name: Bootstrap yay (yay-bin from AUR)
  when: yay_check.rc != 0
  block:
    - name: Clone yay-bin
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: /tmp/yay-bin
        version: master
        force: true

    - name: Build and install yay-bin (must run as non-root)
      ansible.builtin.command:
        cmd: makepkg -si --noconfirm
        chdir: /tmp/yay-bin

    - name: Cleanup yay build directory
      ansible.builtin.file:
        path: /tmp/yay-bin
        state: absent

- name: Upgrade all AUR packages
  kewlfft.aur.aur:
    upgrade: true
    use: yay
  tags: [never, maintenance]
