---
- name: Install neovim deps from official repos
  become: true
  community.general.pacman:
    name:
      - lazygit
      - tree-sitter
    state: present

- name: Install npm-based neovim deps
  become: true
  become_user: "{{ target_user }}"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
    executable: "{{ node_bin_path }}/npm"
  loop:
    - tree-sitter-cli
    - neovim

- name: Upgrade npm-based neovim deps
  become: true
  become_user: "{{ target_user }}"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: latest
    executable: "{{ node_bin_path }}/npm"
  loop:
    - tree-sitter-cli
    - neovim
  tags: [never, maintenance]
