---
- name: Install formatters/linters from official repos
  become: true
  community.general.pacman:
    name:
      - python-black
      - python-ruff
      - stylua
      - shfmt
    state: present

- name: Install npm-based formatters/linters
  become: true
  become_user: "{{ target_user }}"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
    executable: "{{ node_bin_path }}/npm"
  loop:
    - eslint
    - "@fsouza/prettierd"
    - prettier

- name: Upgrade npm-based formatters/linters
  become: true
  become_user: "{{ target_user }}"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: latest
    executable: "{{ node_bin_path }}/npm"
  loop:
    - eslint
    - "@fsouza/prettierd"
    - prettier
  tags: [never, maintenance]
