---
- name: Install LSP servers from official repos
  become: true
  community.general.pacman:
    name:
      - clang
      - pyright
      - zls
      - lua-language-server
      - gopls
      - rust-analyzer
      - bash-language-server
      - yaml-language-server
      - terraform-ls
    state: present

- name: Install npm-based LSP servers
  become: true
  become_user: "{{ target_user }}"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
    executable: "{{ node_bin_path }}/npm"
  loop:
    - typescript-language-server
    - "@vue/language-server"
    - "@astrojs/language-server"

- name: Upgrade npm-based LSP servers
  become: true
  become_user: "{{ target_user }}"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: latest
    executable: "{{ node_bin_path }}/npm"
  loop:
    - typescript-language-server
    - "@vue/language-server"
    - "@astrojs/language-server"
  tags: [never, maintenance]
