---
- name: Install sudo-context CLI basics
  become: true
  community.general.pacman:
    name:
      - wget
      - curl
      - git
      - gnupg
      - less
      - zip
      - unzip
      - rsync
      - dnsutils
      - cliphist
    state: present
    update_cache: true
