---
- name: Install Hyprland compositor + portal + companions
  become: true
  community.general.pacman:
    name:
      - hyprland
      - aquamarine
      - hyprutils
      - hyprlang
      - hyprgraphics
      - hyprwayland-scanner
      - hyprcursor
      - xdg-desktop-portal-hyprland
      - hyprpicker
      - grim
      - slurp
      - uwsm
    state: present


- name: Ensure xdg-desktop-portal config dir exists
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.config/xdg-desktop-portal"
    state: directory
    mode: '0755'

- name: Configure Hyprland portals
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.copy:
    dest: "{{ ansible_facts.env.HOME }}/.config/xdg-desktop-portal/hyprland-portals.conf"
    mode: '0644'
    content: |
      [preferred]
      default=hyprland;gtk
      org.freedesktop.impl.portal.FileChooser=gtk
