---
- name: Install KDE Plasma + portal
  become: true
  community.general.pacman:
    name:
      - plasma
      - plasma-wayland-session
      - kde-applications-meta
      - xdg-desktop-portal-kde
    state: present
