---
- name: Install KDE additional tools
  become: true
  community.general.pacman:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-kde
      - gnome-keyring
      - polkit-kde-agent
    state: present
