---
- name: Install Niri compositor + portal
  become: true
  community.general.pacman:
    name:
      - niri
      - xwayland-satellite
      - xdg-desktop-portal-gnome
      - swayidle
    state: present

- name: Ensure xdg-desktop-portal config dir exists
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.config/xdg-desktop-portal"
    state: directory
    mode: '0755'

- name: Configure Niri portals
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.copy:
    dest: "{{ ansible_facts.env.HOME }}/.config/xdg-desktop-portal/niri-portals.conf"
    mode: '0644'
    content: |
      [preferred]
      default=gnome;gtk
      org.freedesktop.impl.portal.FileChooser=kde
