---
- name: Install gaming packages from official repos
  become: true
  community.general.pacman:
    name:
      - steam
      - gamescope
      - gamemode
      - lib32-gamemode
      - mangohud
      - lib32-mangohud
      - goverlay
      - vkbasalt
      - lib32-vkbasalt
      - wine
      - winetricks
    state: present
    update_cache: true

- name: Install gaming packages from AUR
  kewlfft.aur.aur:
    name:
      - heroic-games-launcher-bin
      - protonup-qt-bin
    state: present
    use: yay
