---
- name: Include system enhancements tasks
  ansible.builtin.include_tasks: system-enhancements.yml
  tags: [system, enhancements]

- name: Include network services tasks
  ansible.builtin.include_tasks: network-services.yml
  tags: [network, services]

- name: Enable fstrim.timer for SSD trim
  become: true
  ansible.builtin.systemd_service:
    name: fstrim.timer
    enabled: true
    state: started
  tags: [system, ssd]
