---
- name: Install network services packages
  become: true
  community.general.pacman:
    name:
      - networkmanager
      - tailscale
      - openssh
      - firewalld
    state: present

- name: Enable NetworkManager
  become: true
  ansible.builtin.systemd_service:
    name: NetworkManager
    enabled: true
    state: started

- name: Enable Tailscale
  become: true
  ansible.builtin.systemd_service:
    name: tailscaled
    enabled: true
    state: started

- name: Enable OpenSSH
  become: true
  ansible.builtin.systemd_service:
    name: sshd
    enabled: true
    state: started

- name: Enable firewalld
  become: true
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: true
    state: started

- name: Open LocalSend ports (TCP/UDP 53317)
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 53317/tcp
    - 53317/udp
