---
- name: Install audio + bluetooth stack
  become: true
  community.general.pacman:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - lib32-pipewire
      - lib32-pipewire-jack
      - wireplumber
      - sof-firmware
      - rtkit
      - bluez
      - bluez-utils
    state: present
    update_cache: true

- name: Check if Bluetooth main.conf exists
  ansible.builtin.stat:
    path: /etc/bluetooth/main.conf
  register: bluetooth_conf

- name: Enable Bluetooth experimental features
  become: true
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^#?Experimental\s*='
    line: 'Experimental = true'
    insertafter: '^\[General\]'
    state: present
  when: bluetooth_conf.stat.exists
  notify: Restart Bluetooth

- name: Enable rtkit-daemon
  become: true
  ansible.builtin.systemd_service:
    name: rtkit-daemon
    enabled: true
    state: started

- name: Enable Bluetooth service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    state: started
