---
- name: Install lm_sensors
  become: true
  community.general.pacman:
    name: lm_sensors
    state: present

- name: Install CoolerControl + CoreCtrl from AUR
  kewlfft.aur.aur:
    name:
      - coolercontrol-bin
      - corectrl
    state: present
    use: yay

- name: Enable CoolerControl daemon
  become: true
  ansible.builtin.systemd_service:
    name: coolercontrold
    enabled: true
    state: started
